### ISSUE TITLE
Inconsistency between ExecutionPlannerFactory and Configuration

### ISSUE THREAD

**Issue by dobraczka** [AKSW/LIMES-dev#22]
The default executionPlan of the Configuration class is "simple" which is unknown to ExecutionPlannerFactory which has "default" instead. So one or the other has to be changed.

**Comment by Kleanthi** [comment]
There is a misconception about the the ExecutionPlan and the ExecutionPlanner. There are two different things. For the moment we don't choose between different execution plans, there is only one, the NestedPlan that is returned by all planners. Also I have noticed some things that should be fixed in the configuration class regarding planners and engines.
