### ISSUE TITLE
acceptance settings doesn't seem to work?

### ISSUE THREAD

**Issue by ziqizhang** [AKSW/LIMES-dev#92]
Hi

I tried to set the acceptance threshold to really low and also require triples to be written with a particular relation but this does not seem to work.

My config (complete file here: https://drive.google.com/file/d/0BwMotMkSrggXNzJsaThwODFtbHc/view?usp=sharing)

`<METRIC>ADD(0.25*set_jaccard(x.on, y.on),0.25*set_jaccard(x.omn, y.omn),0.25*set_jaccard(x.omu, y.omu),0.25*set_jaccard(x.peu, y.peu))</METRIC>`	
`	<ACCEPTANCE>`
`		<THRESHOLD>0.1</THRESHOLD>`
`		<FILE>output.nt</FILE>`
`		<RELATION>sd:sameAs</RELATION>`
`	</ACCEPTANCE>`

However I change `THRESHOLD` or `RELATION`, my output always looks like below, with exactly same number of matches:

`<https://w3id.org/scholarlydata/organisation/max-planck-institute-for-informatics>	<https://w3id.org/scholarlydata/organisation/max-planck-institute-for-informatics>	2.0`
`<https://w3id.org/scholarlydata/organisation/mit-csail>	<https://w3id.org/scholarlydata/organisation/mit-csail>	2.0`

I tried with threshold=0.9 to begin with, and lowered it to 0.1, but the same mappings are produced. Also I thought the output should be 

`<https://w3id.org/scholarlydata/organisation/max-planck-institute-for-informatics> <sd:sameAs> <https://w3id.org/scholarlydata/organisation/max-planck-institute-for-informatics>` 

but it seems that the relation I defined did not get used.

Any suggestions please?

Thanks

**Comment by Kleanthi** [comment]
The similarity of your source and target instances is 2.0; as a result both 0.1 and 0.9 thresholds will accept them as pairs.

**Comment by ziqizhang** [comment]
Thanks for the quick reply Kleanthi

Both the source and target has around 400 URIs to be matched. But the output only returns about 50 pairs of matched URIs, all with a score of 2.0.

I would expect some pairs to have lower scores, say, in the range of [0.0, 2.0]. Hence if I lower the threshold, I should see more pairs get picked up in the output? However this is not the case. If im wrong about what the threshold means please correct me.

Also could you please comment on the RELATION tag, i.e., why the output is not producing mappings using the relation. Again if I misunderstood anything please correct me.

Many thanks!

**Comment by Kleanthi** [comment]
If you are using the same link specification, same source and target
description and you change the threshold, then it is possible that you will
receive the same pairs over and over again as output, because your input
stays always the same. As I explained you, if the output pairs have scores
above 0.9, then lowering the threshold will not affect the output.

Regarding the output format, what type of output (<OUTPUT></OUTPUT> tag)
are you choosing in your configuration file? Is it TAB? If yes, then the
output will be in the form (source, target, score). Please try N3 and I
think your output will be fine. Also please check this link
https://github.com/AKSW/LIMES-dev/blob/master/limes-core/manual/user_manual/configuration_file/output.md

On behalf of the LIMES team,
Kleanthi

**Comment by ziqizhang** [comment]
Thanks!
